# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'UITableLatest' do

  use_frameworks!

  # Pods for UITableLatest

    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'

end
